#baseURL = 'http://localhost:1313'
baseURL = 'https://greycatgames.com'
languageCode = 'en-us'
title = 'Grey Cat Games'
theme = "greycat"
favicon = "/images/favicon.ico"

[params]

[menu]
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "Games"
url = "/games/"
weight = 2
[[menu.main]]
name = "Blog"
url = "/blog/"
weight = 3
[[menu.main]]
name = "Contact"
url = "/contact/"
weight = 4
