#baseURL = 'http://localhost:1313'
baseURL = 'https://greycatgames.com/'
languageCode = 'en-us'
title = 'Grey Cat Games'
theme = "greycat"

[params]
favicon = "/images/favicon.ico"

description = "Grey Cat Games - Indie games studio based in Portsmouth, UK"
keywords = ["indie games", "video games", "Grey Cat Games", "Hugo", "game development", "game dev"]

# Menu
[menu]
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "Games"
url = "/games/"
weight = 2
[[menu.main]]
name = "Blog"
url = "/blog/"
weight = 3
[[menu.main]]
name = "Contact"
url = "/contact/"
weight = 4

relativeURLs = true
canonifyURLs = true